apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://postgresql:5432/sampledb
            - name: DB_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: postgresql
                   key: database-user
            - name: DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: postgresql
                   key: database-password
            - name: FLYWAY_USER
              valueFrom:
                 secretKeyRef:
                   name: postgresql
                   key: database-user
            - name: FLYWAY_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: postgresql
                   key: database-password
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift"