export jdbc_url="jdbc:postgresql://localhost:5432/sampledb"
export jdbc_user="pguser"
export jdbc_password="pgpass"
export FLYWAY_URL="jdbc:postgresql://localhost:5432/sampledb"
export FLYWAY_USER="pguser"
export FLYWAY_PASSWORD="pgpass"
